#!/bin/bash


read -p "Select a mode for interface. [tun] or [tap]? " mode

read -p "Enter Device Name : " dev_name

if [ $mode == "tun" ]
then
	sudo ip tuntap add name $dev_name mode tun
	
elif [ $mode == "tap" ]
then
	sudo ip tuntap add name $dev_name mode tap
else
	sudo echo "Error: unvalid mode."
	exit 1
fi


#IP address is waiting from user

read -p "Enter ip address: " ip_address

if  ! [[ $ip_address =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	sudo echo "Error: unvalid ip address."
	exit 1
fi


#Netmask is waiting from user. If ıt is valid device is created.

read -p "Enter netmask: " netmask

if ! [[ $netmask -ge 0  && $netmask -lt 32 ]]
then

	sudo echo "Error: unvalid netmask."
	exit 1
fi

#device name

sudo ip address add $ip_address/$netmask dev $dev_name
sudo ip link set $dev_name up




