#!/bin/bash

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

tempfile=$(tempfile 2>/dev/null) || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15


dialog --title "BladeRf Driver" --clear \
        --msgbox "This is a user interface for setting BladeRF parameters. User can set miscellaneous parameters such as bandwith, frequency gain. To continue please enter \"OK\" button. " 10 60 2> $tempfile

retval=$?

case $retval in
  $DIALOG_OK)
    ;;
  $DIALOG_ESC)
    if test -s $tempfile ; then
      cat $tempfile 
      exit 1
    else
      exit 1
    fi
    ;;
esac



ans=$(dialog --backtitle "Dialog Form Example" --title "TUN/TAP Interface Parameters" \
--ok-label "Submit" \
--form "\n Please enter TUN/TAP interface parameters." 		20 60 16 \
"Select interface type:" 1 1 "" 	1 25 25 30 \
"Enter device name:" 	 2 1 "" 	2 25 25 30 \
"Enter ip address:" 	 3 1 "" 	3 25 25 30 \
"Enter subnet:" 	 4 1 "" 	4 25 25 30 2>&1 >/dev/tty)

#echo -e "\n\n\n\nAnswer=[${ans}]"
i=0
while read -r line; do
   ((i++))
   declare var$i="${line}"
done <<< "${ans}"

echo "$var1"

if [ $var1 == "tun" ]
then
	sudo ip tuntap add name $var2 mode tun
	
elif [ $var1 == "tap" ]
then
	sudo ip tuntap add name $var2 mode tap
else
	sudo echo "Error: unvalid mode."
	exit 1
fi


#IP address is waiting from user

if  ! [[ $var3 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	sudo echo "Error: unvalid ip address."
	exit 1
fi


#Netmask is waiting from user. If ıt is valid device is created.



if ! [[ $var4 -ge 0  && $var4 -lt 32 ]]
then

	sudo echo "Error: unvalid netmask."
	exit 1
fi

#device name

sudo ip address add $var3/$var4 dev $var2
sudo ip link set $var2 up




